-- Run this in Supabase SQL Editor

-- Step 1: Create table
CREATE TABLE IF NOT EXISTS catalogue_brands (
  id bigserial PRIMARY KEY,
  catalogue_id text NOT NULL DEFAULT 'inventario-2026',
  name text NOT NULL,
  korean_name text,
  instagram text,
  post text,
  category text,
  country text DEFAULT 'KR',
  booth text,
  url text,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE catalogue_brands DISABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS catalogue_brands_catalogue_id_idx ON catalogue_brands (catalogue_id);

-- Step 2: Remove old data if any
DELETE FROM catalogue_brands WHERE catalogue_id = 'inventario-2026';

-- Step 3: Insert all brands with correct booth numbers
INSERT INTO catalogue_brands (catalogue_id, name, korean_name, category, country, booth, sort_order) VALUES
  ('inventario-2026', 'mt × rolledpaint', 'mt × 롤드페인트', 'Small Thing', 'KR', 'A02', 0),
  ('inventario-2026', 'LIMPA LIMPA', '겨울엔토스트가좋아', 'Small Thing', 'KR', 'B02', 1),
  ('inventario-2026', 'FRUITFRIES', '후르츠후라이', 'Small Thing', 'KR', 'B03', 2),
  ('inventario-2026', 'IWAKO', '이와코', 'Small Thing', 'JP', 'B06', 3),
  ('inventario-2026', 'HWF.RISOCLUB', '하우풀리소클럽', 'Small Thing', 'KR', 'C03', 4),
  ('inventario-2026', 'GOOBER', '구버', 'Small Thing', 'KR', 'E03', 5),
  ('inventario-2026', 'MICIA', '미씨아', 'Small Thing', 'KR', 'E05', 6),
  ('inventario-2026', 'LYRA', '리라', 'Small Thing', 'INTL', 'E05', 7),
  ('inventario-2026', 'LIFE&PIECES', '라이프앤피시스', 'Small Thing', 'INTL', 'F01', 8),
  ('inventario-2026', 'IROHA', '이로하', 'Small Thing', 'JP', 'F03', 9),
  ('inventario-2026', 'FLAGG', '플래그', 'Small Thing', 'KR', 'F07', 10),
  ('inventario-2026', 'SOME MOOD DESIGN', '썸무드디자인', 'Small Thing', 'KR', 'F08', 11),
  ('inventario-2026', 'BOKI', '보키', 'Small Thing', 'KR', 'F09', 12),
  ('inventario-2026', 'SUKIDOKI', '수키도키', 'Small Thing', 'KR', 'G03', 13),
  ('inventario-2026', 'AHMUGAE_C', '아무개씨', 'Small Thing', 'KR', 'G06', 14),
  ('inventario-2026', 'SANBY', '산비', 'Small Thing', 'JP', 'G07', 15),
  ('inventario-2026', '0.1', '0.1', 'Small Thing', 'KR', 'H02', 16),
  ('inventario-2026', 'MINIMONI', '미니모니', 'Small Thing', 'KR', 'H05', 17),
  ('inventario-2026', 'HITOTOKI', '히토토키', 'Small Thing', 'JP', 'H06', 18),
  ('inventario-2026', 'PRESENT PRESENT', '프레젠트프레젠트', 'Small Thing', 'KR', 'H07', 19),
  ('inventario-2026', 'KIOSK KIOSK', '키오스크키오스크', 'Small Thing', 'KR', 'H09', 20),
  ('inventario-2026', 'LITTLE TEMPO DESIGN', '리틀템포디자인', 'Small Thing', 'KR', 'I08', 21),
  ('inventario-2026', 'ICONIC', '아이코닉', 'Small Thing', 'KR', 'I09', 22),
  ('inventario-2026', 'PRELUDE STUDIO', '프렐류드스튜디오', 'Small Thing', 'KR', 'J03', 23),
  ('inventario-2026', 'NO NOT NEVER', '노낫네버', 'Small Thing', 'KR', 'J09', 24),
  ('inventario-2026', 'PULPUL', '풀풀', 'Small Thing', 'KR', 'J10', 25),
  ('inventario-2026', 'RIFLE PAPER CO.', '라이플페이퍼', 'Small Thing', 'INTL', 'L02', 26),
  ('inventario-2026', 'GEEHEY', '지헤이', 'Small Thing', 'KR', 'L04', 27),
  ('inventario-2026', 'SUATELIER', '슈아뜰리에', 'Small Thing', 'KR', 'L06', 28),
  ('inventario-2026', 'FABER-CASTELL', '파버카스텔', 'Writing & Drawing', 'INTL', 'A03', 29),
  ('inventario-2026', 'KAKIMORI', '카키모리', 'Writing & Drawing', 'JP', 'A04', 30),
  ('inventario-2026', 'BLACKHEART', '흑심', 'Writing & Drawing', 'KR', 'A05', 31),
  ('inventario-2026', 'CARAN D''ACHE', '까렌다쉬', 'Writing & Drawing', 'INTL', 'A08', 32),
  ('inventario-2026', 'SAILOR', '세일러', 'Writing & Drawing', 'JP', 'A09', 33),
  ('inventario-2026', 'SHIELDCOLORS', '쉴드물감', 'Writing & Drawing', 'KR', 'A10', 34),
  ('inventario-2026', 'COPIC', '코픽', 'Writing & Drawing', 'JP', 'A11', 35),
  ('inventario-2026', 'WEARINGEUL', '글입다', 'Writing & Drawing', 'KR', 'C02', 36),
  ('inventario-2026', 'DOMINANT INDUSTRY', '도미넌트인더스트리', 'Writing & Drawing', 'KR', 'E01', 37),
  ('inventario-2026', 'KOREA PILOT', '한국파이롯트', 'Writing & Drawing', 'KR', 'E04', 38),
  ('inventario-2026', 'ZEBRA', '제브라', 'Writing & Drawing', 'JP', 'F06', 39),
  ('inventario-2026', 'PENTEL', '펜텔', 'Writing & Drawing', 'JP', 'H06', 40),
  ('inventario-2026', 'RAYMAY KEPT', '레이메이 켑트', 'Writing & Drawing', 'JP', 'H06', 41),
  ('inventario-2026', 'WOODHI', '우디', 'Writing & Drawing', 'JP', 'H06', 42),
  ('inventario-2026', 'UNI', '유니', 'Writing & Drawing', 'JP', 'J01', 43),
  ('inventario-2026', 'JACQUES HERBIN', '자크 허빈', 'Writing & Drawing', 'INTL', 'J07', 44),
  ('inventario-2026', 'GLOBE CHEMICAL', '지구화학', 'Writing & Drawing', 'KR', 'L01', 45),
  ('inventario-2026', 'CLIPEN', '클립펜', 'Writing & Drawing', 'KR', 'L03', 46),
  ('inventario-2026', 'POV', '포인트오브뷰', 'Daily Finds', 'KR', 'A06', 47),
  ('inventario-2026', 'POV × HELLO KITTY', '포인트오브뷰 × 헬로키티', 'Daily Finds', 'KR', 'B01', 48),
  ('inventario-2026', 'THENCE', '덴스', 'Daily Finds', 'KR', 'B04', 49),
  ('inventario-2026', 'MEET ME', '밑미', 'Daily Finds', 'KR', 'B05', 50),
  ('inventario-2026', 'NOBIGDEAL', '노빅딜', 'Daily Finds', 'KR', 'D03', 51),
  ('inventario-2026', 'GONGYEGA', '공예가', 'Daily Finds', 'KR', 'E02', 52),
  ('inventario-2026', 'TIETOA', '티에토아', 'Daily Finds', 'KR', 'F04', 53),
  ('inventario-2026', 'KITTY BUNNY PONY', '키티버니포니', 'Daily Finds', 'KR', 'F05', 54),
  ('inventario-2026', 'OH, LOLLY DAY!', '오롤리데이', 'Daily Finds', 'KR', 'G04', 55),
  ('inventario-2026', 'YOUR-MIND', '유어마인드', 'Daily Finds', 'KR', 'H03', 56),
  ('inventario-2026', 'onemorebag', '원모어백', 'Daily Finds', 'KR', 'H04', 57),
  ('inventario-2026', 'SAILORS', '세일러즈', 'Daily Finds', 'KR', 'H08', 58),
  ('inventario-2026', 'OIMU', '오이뮤', 'Daily Finds', 'KR', 'I04', 59),
  ('inventario-2026', 'HOWkidsFUL', '하우키즈풀', 'Daily Finds', 'KR', 'J05', 60),
  ('inventario-2026', 'FRANZ', '프란츠', 'Daily Finds', 'KR', 'J06', 61),
  ('inventario-2026', 'CIRCUS BOY BAND', '서커스보이밴드', 'Daily Finds', 'KR', 'L07', 62),
  ('inventario-2026', 'TRAVELER''S COMPANY', '트래블러스컴퍼니', 'Daily Finds', 'JP', 'L08', 63),
  ('inventario-2026', 'DOOSUNG PAPER', '두성종이', 'Paper', 'KR', 'A01', 64),
  ('inventario-2026', 'PAPER TAILOR', '페이퍼테일러', 'Paper', 'KR', 'A12', 65),
  ('inventario-2026', 'GONGJANG', '그린디자인웍스 공장', 'Paper', 'KR', 'C04', 66),
  ('inventario-2026', 'MOHS', '모스', 'Paper', 'KR', 'C05', 67),
  ('inventario-2026', 'O-CHECK', '오첵', 'Paper', 'KR', 'C06', 68),
  ('inventario-2026', 'HANSOL PAPER × URBANBOOKS', '한솔제지 × 어반북스', 'Paper', 'KR', 'C08', 69),
  ('inventario-2026', 'SAMWON PAPER', '삼원페이퍼', 'Paper', 'KR', 'C10', 70),
  ('inventario-2026', 'BE ON D', '비온뒤', 'Paper', 'KR', 'G02', 71),
  ('inventario-2026', 'WHENIWASYOUNG', '웬아이워즈영', 'Paper', 'KR', 'G05', 72),
  ('inventario-2026', 'KAWI', '가위', 'Paper', 'KR', 'H01', 73),
  ('inventario-2026', 'TROLLS PAPER', '트롤스페이퍼', 'Paper', 'INTL', 'I01', 74),
  ('inventario-2026', 'YANGJISA', '양지사', 'Paper', 'KR', 'I02', 75),
  ('inventario-2026', 'SOSOMOONGOO', '소소문구', 'Paper', 'KR', 'I03', 76),
  ('inventario-2026', 'PAPER PLATE', '페이퍼플레이트', 'Paper', 'KR', 'I05', 77),
  ('inventario-2026', 'GEULWOL', '글월', 'Paper', 'KR', 'I07', 78),
  ('inventario-2026', 'COMPOSITION STUDIO', '컴포지션 스튜디오', 'Paper', 'KR', 'J02', 79),
  ('inventario-2026', 'MOLESKINE', '몰스킨', 'Paper', 'INTL', 'J04', 80),
  ('inventario-2026', 'RHODIA', '로디아', 'Paper', 'INTL', 'J07', 81),
  ('inventario-2026', 'PAPERIAN', '페이퍼리안', 'Paper', 'KR', 'J11', 82),
  ('inventario-2026', 'THE COMPLETIST', '더컴플리티스트', 'Paper', 'INTL', 'L02', 83),
  ('inventario-2026', 'PENCO®', '펜코', 'Office & Desk', 'JP', 'B08', 84),
  ('inventario-2026', 'LOGITECH', '로지텍', 'Office & Desk', 'INTL', 'C01', 85),
  ('inventario-2026', 'KOKUYO', '고쿠요', 'Office & Desk', 'JP', 'C11', 86),
  ('inventario-2026', 'ILOOM', '일룸', 'Office & Desk', 'KR', 'D01', 87),
  ('inventario-2026', 'WIP', '워크인프로그래스', 'Office & Desk', 'KR', 'D05', 88),
  ('inventario-2026', 'BUYHEARTS', '바이하츠', 'Office & Desk', 'KR', 'E06', 89),
  ('inventario-2026', 'MAGAZINE C', '매거진C', 'Office & Desk', 'KR', 'F02', 90),
  ('inventario-2026', 'NELNA', '낼나', 'Office & Desk', 'KR', 'G01', 91),
  ('inventario-2026', 'MOTEMOTE', '모트모트', 'Office & Desk', 'KR', 'I06', 92),
  ('inventario-2026', 'PLUS', '프러스', 'Office & Desk', 'JP', 'J08', 93),
  ('inventario-2026', 'CRAFT DESIGN TECHNOLOGY', '크래프트디자인테크놀로지', 'Office & Desk', 'JP', 'L02', 94),
  ('inventario-2026', 'SANRO', '산로', 'Office & Desk', 'KR', 'L05', 95),
  ('inventario-2026', 'MARK''S', '마크스', 'Kiosk', 'JP', 'K01', 96),
  ('inventario-2026', 'OUIE', '우이', 'Kiosk', 'KR', 'K02', 97),
  ('inventario-2026', 'MINDOBITTO', '민도비또', 'Kiosk', 'KR', 'K03', 98),
  ('inventario-2026', 'HWARANG', '화랑', 'Kiosk', 'KR', 'K04', 99),
  ('inventario-2026', 'DONKY CONTÉ', '동키콩테', 'Kiosk', 'KR', 'K05', 100),
  ('inventario-2026', 'ANTERIQUE', '안테리크', 'Kiosk', 'JP', 'K06', 101),
  ('inventario-2026', 'SUI GOUACHE', '수이과슈', 'Kiosk', 'KR', 'K07', 102),
  ('inventario-2026', 'MEWMEWBEAM', '냥냥빔', 'Kiosk', 'KR', 'K08', 103),
  ('inventario-2026', 'NOH YONG-WON', '노용원 혁필화', 'Kiosk', 'KR', 'K09', 104),
  ('inventario-2026', 'THE HANGEUL', '더한글', 'Workshop', 'KR', 'A07', 105),
  ('inventario-2026', 'SEOUL DESIGN FOUNDATION', '서울디자인재단 × 서울스티커샵', 'Workshop', 'KR', 'B07', 106),
  ('inventario-2026', 'PaTI', '파티', 'Workshop', 'KR', 'C07', 107),
  ('inventario-2026', 'SAMWON PAPER WORKSHOP', '삼원페이퍼 워크숍', 'Workshop', 'KR', 'C09', 108),
  ('inventario-2026', 'KIOSK KIOSK WORKSHOP', '키오스크키오스크 문구클럽 & 워크숍', 'Workshop', 'KR', 'D04', 109),
  ('inventario-2026', 'TRAVELER''S COMPANY WORKSHOP', '트래블러스컴퍼니 워크숍', 'Workshop', 'JP', 'L09', 110),
  ('inventario-2026', 'NAVER LOUNGE', '네이버 라운지', 'Common', 'KR', 'M01', 111),
  ('inventario-2026', 'REMASTERED', '리마스터드', 'Common', 'KR', 'M02', 112),
  ('inventario-2026', 'Layer''s Together', '레이어스투게더', 'Common', 'KR', 'M03', 113),
  ('inventario-2026', 'LOUNGE', '휴게공간', 'Common', 'KR', 'M04', 114);

-- Total: 115 brands
